# Generated by Django 2.0.2 on 2018-02-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='ticket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='uni.StudentTicket'),
            preserve_default=False,
        ),
    ]
