# Generated by Django 2.0.2 on 2018-02-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20180228_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentticket',
            name='numbers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
