# Generated by Django 2.0.2 on 2018-02-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_studentticket_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='extra_classes',
            field=models.ManyToManyField(to='uni.ExtraClass', verbose_name='Student extra classes'),
        ),
    ]
