# Generated by Django 2.0.2 on 2018-02-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('register_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('average_mark', models.DecimalField(decimal_places=2, max_digits=3)),
                ('num_studies', models.IntegerField()),
                ('description_about', models.TextField()),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('resume', models.FileField(upload_to='resumes')),
            ],
        ),
    ]
